//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartamentEquipment
    {
        public int id_depEquip { get; set; }
        public Nullable<int> id_dep { get; set; }
        public Nullable<int> id_equipdep { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
