//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseEquipment
    {
        public int id_warehouseequipment { get; set; }
        public Nullable<int> id_equipment { get; set; }
        public string count { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
